#This will create as container...push it to GIT...and then deploy to docker hub

FROM ubuntu:14.04
MAINTAINER harikrishna nallamala

#Create a directory newdir and touch mynewfile
RUN mkdir newdir
RUN touch /newdir/mynewfile
RUN echo 'this is my new container to make image and then push to hub' >/newdir/mynewfile

